FROM python:3.8.16-bullseye
ENV PYTHONUNBUFFERED 1


RUN apt update && apt install -y xvfb tini
RUN wget https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_106.0.5249.61-1_amd64.deb
RUN apt update && apt install -y ./google-chrome-stable_106.0.5249.61-1_amd64.deb
