FROM python:3.11.3-bullseye
ENV PYTHONUNBUFFERED 1


RUN apt update && apt install -y xvfb tini
RUN wget https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_112.0.5615.121-1_amd64.deb
RUN apt update && apt install -y ./google-chrome-stable_112.0.5615.121-1_amd64.deb
